# Generated by Django 4.0.6 on 2022-08-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
