# Generated by Django 4.0.6 on 2022-08-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_cartitem_quantity_alter_line_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default_item_image.jpg', null=True, upload_to='items'),
        ),
    ]
